### ISSUE TITLE
The most recent commit for 6.x breaks build process.

### ISSUE THREAD

**Issue by nlighteneddesign** [pantheon-systems/docker-build-tools-ci#51] opened 2020-01-29 19:38 UTC
The following commit: 4dc7a737984f54c280a5e16f2e7e551a6c0365e0
breaks the node-sass implementation for a client's deployment process.

Since there are no releases there was no way to roll back the container and I was forced to switch back to the nodejs tag.

Here are the CI errors:
error /home/tester/web/themes/custom_theme/node_modules/bourbon-neat/node_modules/node-sass: Command failed.

**Comment by greg-1-anderson** [comment] 2020-01-29 21:01
I think that the real problem here is that our container does not provide strong control over which version of the node container you get. The above commit has no relationship to node; backing it out would not solve the problem, as the cause is probably due to the fact that a different parent container was selected due to upstream changes.

It's probably better, wherever possible, to run your node tasks in a different CircleCI step so that you can pick your own node container rather than relying on whatever happens to be in this one.

**Comment by kporras07** [comment] 2021-09-21 02:06
Closing as Greg's comment suggests a good fix without any change needed in this repo. Feel free to reopen if needed.

**Closed as completed by kporras07** 2021-09-21 02:06 UTC
